<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="description" content="Machine-learning : Machine Learning Coursera">

    <link rel="stylesheet" type="text/css" media="screen" href="stylesheets/stylesheet.css">

    <title>Machine-learning</title>
  </head>

  <body>

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="https://github.com/Audraa/Machine-Learning">View on GitHub</a>

          <h1 id="project_title">Machine-learning</h1>
          <h2 id="project_tagline">Machine Learning Coursera</h2>

            <section id="downloads">
              <a class="zip_download_link" href="https://github.com/Audraa/Machine-Learning/zipball/master">Download this project as a .zip file</a>
              <a class="tar_download_link" href="https://github.com/Audraa/Machine-Learning/tarball/master">Download this project as a tar.gz file</a>
            </section>
        </header>
    </div>

    <!-- MAIN CONTENT -->
    <div id="main_content_wrap" class="outer">
      <section id="main_content" class="inner">
        <p></p>

<p></p>Machine Learning Course Project



<p>

</p>



code{white-space: pre;}

<p></p>




  pre:not([class]) {
    background-color: white;
  }




<p></p>

<p></p>


.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}


<div>


<div id="header">
<h1>
<a id="machine-learning-course-project" class="anchor" href="#machine-learning-course-project" aria-hidden="true"><span class="octicon octicon-link"></span></a>Machine Learning Course Project</h1>
<h4>
<a id="coursera-student-a" class="anchor" href="#coursera-student-a" aria-hidden="true"><span class="octicon octicon-link"></span></a><em>Coursera Student A</em>
</h4>
<h4>
<a id="15-february-2015" class="anchor" href="#15-february-2015" aria-hidden="true"><span class="octicon octicon-link"></span></a><em>15 February 2015</em>
</h4>
</div>

<div id="summary">
<h1>
<a id="summary" class="anchor" href="#summary" aria-hidden="true"><span class="octicon octicon-link"></span></a>Summary</h1>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, the goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a> (see the section on the Weight Lifting Exercise Dataset).</p>
</div>

<div id="data-analysis">
<h1>
<a id="data-analysis" class="anchor" href="#data-analysis" aria-hidden="true"><span class="octicon octicon-link"></span></a>Data Analysis</h1>
<p>There are several variables including some derived variables in the dataset. The columns that had a lot of null values were removed from the dataset. The same column was then applied to the test data set.</p>
<p>The training data was split into training and test with a ratio of 60% for training and 40% for testing and cross validation.</p>
<p>Results were then reviewed and analysed. Predictions was then made using the original test dataset with 20 observations.</p>
<p>In the analysis the variables were ploted against thier indexes and we can see that the class variable is a good classifier for each of the variables. We investigate further to see if all the variables are required for the prediction.</p>
<p>Given a set of data the model will be able to predict how well a person is doing a give exercise.</p>
<p>The data was partitioned into training(30%) and testing (70%).This ratio was used as the process took too long to complete. Normarlly this would be 60% 0 % ratio. The train method in the caret package. We predict using random forest (rf).</p>
<p>The seed was set to 32343 to make the result reproducible. The model was then cross validated using</p>
</div>

<div id="model">
<h1>
<a id="model" class="anchor" href="#model" aria-hidden="true"><span class="octicon octicon-link"></span></a>Model</h1>
<div id="results">
<h3>
<a id="results" class="anchor" href="#results" aria-hidden="true"><span class="octicon octicon-link"></span></a>Results</h3>
<pre><code>## 
## Call:
##  randomForest(formula = as.factor(class) ~ ., data = training,      ntree = 500) 
##                Type of random forest: classification
##                      Number of trees: 500
## No. of variables tried at each split: 7
## 
##         OOB estimate of  error rate: 0.71%
## Confusion matrix:
##      A    B    C    D    E class.error
## A 3343    4    0    0    1 0.001493429
## B   16 2258    4    1    0 0.009214568
## C    0   17 2033    4    0 0.010223953
## D    0    0   28 1900    2 0.015544041
## E    0    0    3    4 2158 0.003233256</code></pre>
</div>

<div id="predict-test">
<h2>
<a id="predict-test" class="anchor" href="#predict-test" aria-hidden="true"><span class="octicon octicon-link"></span></a>Predict test</h2>
<pre><code>rfpre2&lt;- predict(rfFit2,testing)</code></pre>
<div id="confusion-matrix">
<h3>
<a id="confusion-matrix" class="anchor" href="#confusion-matrix" aria-hidden="true"><span class="octicon octicon-link"></span></a>Confusion Matrix</h3>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2232   12    0    0    0
##          B    0 1503   14    0    0
##          C    0    3 1353   13    2
##          D    0    0    1 1271    3
##          E    0    0    0    2 1437
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9936          
##                  95% CI : (0.9916, 0.9953)
##     No Information Rate : 0.2845          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.9919          
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            1.0000   0.9901   0.9890   0.9883   0.9965
## Specificity            0.9979   0.9978   0.9972   0.9994   0.9997
## Pos Pred Value         0.9947   0.9908   0.9869   0.9969   0.9986
## Neg Pred Value         1.0000   0.9976   0.9977   0.9977   0.9992
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2845   0.1916   0.1724   0.1620   0.1832
## Detection Prevalence   0.2860   0.1933   0.1747   0.1625   0.1834
## Balanced Accuracy      0.9989   0.9940   0.9931   0.9939   0.9981</code></pre>
</div>

<p></p>
</div>

<div id="predicting-results-for-the-test-data-set">
<h2>
<a id="predicting-results-for-the-test-data-set" class="anchor" href="#predicting-results-for-the-test-data-set" aria-hidden="true"><span class="octicon octicon-link"></span></a>Predicting results for the test data set</h2>
<pre><code>print(rfpre2&lt;- predict(rfFit2,testing2))</code></pre>
<pre><code>##  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 
##  B  A  B  A  A  E  D  B  A  A  B  C  B  A  E  E  A  B  B  B 
## Levels: A B C D E</code></pre>
</div>

<p></p>
</div>

<div id="conclusion">
<h1>
<a id="conclusion" class="anchor" href="#conclusion" aria-hidden="true"><span class="octicon octicon-link"></span></a>Conclusion</h1>
<p>The final model gives a 99.3% Accuracy with a confidence interval of 99.1% - 99.5%. The Accuracy lies between this interval. The model predicts that the exercise is being done well (class = A) with a sensitivity of 99.9% and specificity of 99.8.9%. Again for class A prediction both the positive and negetive prediction are high. The model sensitivity and specificity for the other class are are equally very good.</p>
<p>Further more we see the error rates are very low with the exception of class D which is low but slightly higher than all the other error rates.</p>
</div>

<p></p>
</div>







<p>
</p>
      </section>
    </div>

    <!-- FOOTER  -->
    <div id="footer_wrap" class="outer">
      <footer class="inner">
        <p class="copyright">Machine-learning maintained by <a href="https://github.com/Audraa">Audraa</a></p>
        <p>Published with <a href="http://pages.github.com">GitHub Pages</a></p>
      </footer>
    </div>

    

  </body>
</html>
